-- Seed data for Alejandro's Library Dashboard

INSERT INTO books (title, author, year, genre, rating) VALUES
-- 2024 books
('Nature', 'Ralph Waldo Emerson', 2024, 'Philosophy', 4.0),
('Martín Chambi', 'Amanda Hopkinson', 2024, 'Photography', 4.2),
('Between the World and Me', 'Ta-Nehisi Coates', 2024, 'Memoir', 4.6),
('I''m Glad My Mom Died', 'Jennette McCurdy', 2024, 'Memoir', 4.5),
('Bullshit Jobs', 'David Graeber', 2024, 'Nonfiction', 4.3),
('The Will to Change', 'bell hooks', 2024, 'Nonfiction', 4.4),
('The Myth of Sisyphus', 'Albert Camus', 2024, 'Philosophy', 4.4),
('Stoner', 'John Williams', 2024, 'Fiction', 4.3),
('Project Hail Mary', 'Andy Weir', 2024, 'Sci-Fi', 4.6),
('The Metamorphosis', 'Franz Kafka', 2024, 'Classic', 4.2),
('The Lost World', 'Michael Crichton', 2024, 'Adventure', 4.0),
('99 Poems to Cure Whatever''s Wrong With You or Create the Problems You Need', 'Sam Pink', 2024, 'Poetry', 4.1),
('Wild', 'Cheryl Strayed', 2024, 'Memoir', 4.2),
('Man''s Search for Meaning', 'Viktor Frankl', 2024, 'Psychology', 4.7),
('A Psalm for the Wild-Built', 'Becky Chambers', 2024, 'Sci-Fi', 4.3),
('A Prayer for the Crown-Shy', 'Becky Chambers', 2024, 'Sci-Fi', 4.4),
('Justice Is Coming', 'Cenk Uygur', 2024, 'Politics', 4.0),
('Crying in H Mart', 'Michelle Zauner', 2024, 'Memoir', 4.4),
('The Secret History', 'Donna Tartt', 2024, 'Fiction', 4.5),
('Remarkably Bright Creatures', 'Shelby Van Pelt', 2024, 'Fiction', 4.4),
('Feast Your Eyes', 'Myla Goldberg', 2024, 'Fiction', 4.1),
('All About Love', 'bell hooks', 2024, 'Nonfiction', 4.6),
('Adult Children of Emotionally Immature Parents', 'Lindsay C. Gibson', 2024, 'Psychology', 4.4),
('Monstrilio', 'Gerardo Sámano Córdova', 2024, 'Fiction', 4.1),
('The Adventures of Pinocchio', 'Carlo Collodi', 2024, 'Classic', 4.0),
('Go Tell It on the Mountain', 'James Baldwin', 2024, 'Classic', 4.5),
('Breakfast of Champions', 'Kurt Vonnegut', 2024, 'Satire', 4.3),
('I Know Why the Caged Bird Sings', 'Maya Angelou', 2024, 'Memoir', 4.7),
('To Be Taught, If Fortunate', 'Becky Chambers', 2024, 'Sci-Fi', 4.2),
('Hard Rain Falling', 'Don Carpenter', 2024, 'Fiction', 4.3),
('Batman: The Long Halloween', 'Jeph Loeb', 2024, 'Graphic Novel', 4.4),
('Batman: Dark Victory', 'Jeph Loeb', 2024, 'Graphic Novel', 4.3),

-- 2025 books
('The Body Keeps the Score', 'Bessel van der Kolk', 2025, 'Psychology', 4.7),
('The Remains of the Day', 'Kazuo Ishiguro', 2025, 'Fiction', 4.5),
('The Spy Who Loved Me', 'Ian Fleming', 2025, 'Thriller', 4.0),
('Demon Copperhead', 'Barbara Kingsolver', 2025, 'Fiction', 4.6),
('Sula', 'Toni Morrison', 2025, 'Fiction', 4.5),
('East of Eden', 'John Steinbeck', 2025, 'Fiction', 4.7),
('The Glass Castle', 'Jeannette Walls', 2025, 'Memoir', 4.4),
('Annihilation', 'Jeff VanderMeer', 2025, 'Sci-Fi', 4.3),
('On Earth We''re Briefly Gorgeous', 'Ocean Vuong', 2025, 'Fiction', 4.6),
('I Who Have Never Known Men', 'Jacqueline Harpman', 2025, 'Fiction', 4.4),
('Dungeon Crawler Carl', 'Matt Dinniman', 2025, 'Sci-Fi', 4.3),
('James', 'Percival Everett', 2025, 'Fiction', 4.6),
('Tomorrow, and Tomorrow, and Tomorrow', 'Gabrielle Zevin', 2025, 'Fiction', 4.6),
('Butcher''s Crossing', 'John Williams', 2025, 'Fiction', 4.3),
('Letters from a Stoic', 'Seneca', 2025, 'Philosophy', 4.5),
('Kafka on the Shore', '村上春樹', 2025, 'Fiction', 4.4),
('Tao Te Ching', 'Lao Tzu', 2025, 'Philosophy', 4.6);
